---
- name: Shard Cluster
  community.mongodb.mongodb_shard:
    login_host: localhost:{{ shard_port }}
    login_user: "{{ admin_user }}"
    login_password: "{{ admin_password }}"
    login_database: admin
    shard: {{ item.shard}}/{{ item.members | join(',') }}
    state: present
  loop: "{{ shard_info }}"