- name: install pbm program
  gather_facts: yes
  hosts: mongodb
  roles:
    - backup1_install_pbm
  vars:
    pbmuser_password: "{{ pbmuser_password }}"
    mongod_port: "{{ mongod_port }}"

- name: add role/user to all shard(config+data)
  gather_facts: yes
  hosts: mongodb:!tags_arbiter:!tags_mongodb_bastion
  roles:
    - backup2_db_backup_role
  vars:
    pbmuser_password: "{{ pbmuser_password }}"
    mongod_port: "{{ mongod_port }}"
    mongo_root_password: "{{ mongo_root_password }}"

- name: shard-wide setting for backup through bastion mongos
  gather_facts: yes
  hosts: tags_mongodb_bastion
  roles:
    - backup3_shardwide_setting
  vars:
    pbmuser_password: "{{ pbmuser_password }}"
    mongod_port: "{{ mongod_port }}"
    mongo_root_password: "{{ mongo_root_password }}"
    MONGODB_CONFIG_SERVER_URI: "{{ MONGODB_CONFIG_SERVER_URI }}"

- name: start pbm_agent service
  gather_facts: yes
  hosts: mongodb:!tags_mongodb_bastion
  roles:
    - backup4_start_agent