---
replica_info:
  tag_replica_set_1:
    shard: rs-shard1
    members:
      - host: ""
        priority: 1
      - host: ""
        priority: 0.5
      - host: ""   # Arbiter
        priority: 0
    arbiter_index: 2
  tag_replica_set_2:
    shard: rs-shard2
    members:
      - host: ""
        priority: 1
      - host: ""
        priority: 0.5
      - host: ""   # Arbiter
        priority: 0
    arbiter_index: 2
  tag_replica_set_3:
    shard: rs-shard3
    members:
      - host: ""
        priority: 1
      - host: ""
        priority: 0.5
      - host: ""   # Arbiter
        priority: 0
    arbiter_index: 2

admin_user: admin
admin_password: ""