---
- name: Add apt key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.4.asc
    state: present

- name: Add mongodb package repository
  apt_repository:
    repo: deb https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse
    state: present

- name: Update apt repository cache
  apt:
    update_cache: yes

- name: Convert Timezone to KST
  timezone:
    name: Asia/Seoul

- name: Install chrony
  apt:
    name: chrony
    state: present

- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Creates chrony directory
  file:
    path: /etc/chrony
    state: directory

- name: Create ntp config file from template
  template:
    src: chrony.conf.template
    dest: /etc/chrony/chrony.conf
  notify:
    - restart chrony

- name: Create directory for private key
  file:
    path: "{{ private_key_path }}"
    state: directory

- name: Create Private Key for mongo access
  copy:
    src: mongo-shard.pem
    dest: "{{ private_key_path }}/{{ private_key }}"
    mode: '0400'
    owner: mongodb
    group: mongodb
