# Global Configuration
ansible_port: <ssh port of mongoDB machine>
ansible_ssh_user: ubuntu
ansible_python_interpreter: <python path>
ansible_ssh_private_key_file: <pem file path>

#install mongodb variable
admin_user: ""
admin_password: ""
shard_admin_user: ""
shard_admin_password: ""

# Every host should be written in (IP(DNS):Port) format
config_members:
  - host: ""          # mongodb-cfg1 (Format : IP(DNS):Port)
    priority: 1
  - host: ""          # mongodb-cfg2
    priority: 0.5
  - host: ""          # mongodb-cfg3
    priority: 0.5

replica_info:
  tag_replica_set_1:
    shard: rs-shard1
    members:
      - host: ""      # mongodb-s1d1
        priority: 1
      - host: ""      # mongodb-s1d1
        priority: 0.5
      - host: ""      # mongodb-s1d3 (Arbiter)
        priority: 0
    arbiter_index: 2
  tag_replica_set_2:
    shard: rs-shard2
    members:
      - host: ""        # mongodb-s2d1
        priority: 1
      - host: ""        # mongodb-s2d2
        priority: 0.5
      - host: ""        # mongodb-s2d3 (Arbiter)
        priority: 0
    arbiter_index: 2
  tag_replica_set_3:
    shard: rs-shard3
    members:
      - host: ""        # mongodb-s3d1
        priority: 1
      - host: ""        # mongodb-s3d2
        priority: 0.5
      - host: ""        # mongodb-s3d3 (Arbiter)
        priority: 0
    arbiter_index: 2

databases: # the list of databases to be sharded
  - identity
  - inventory
  - billing
  - config
  - cost-saving
  - monitoring
  - plugin
  - power-scheduler
  - repository
  - secret
  - statistics

#backup variable
backup_or_not: # True | False

region_of_S3: <region of backup bucket>
bucket_name: <backup bucket name>

access_key_S3: <your-access-key-id-here>
secret_access_key_S3: <your-secret-key-here>

mongod_port: <mongoDB port>
pbmuser_password: <pbmuser password to create>
mongo_config_replset_name: <name of config server replica set>

MONGODB_CONFIG_SERVER_URI: "{{ config_members | map(attribute='host') | join(',') }}/?replicaSet={{ mongo_config_replset_name }}" # no need to edit

stale_criteria: <criteria of old file to be deleted, unit is day>
