---
- name: Add apt key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.4.asc
    state: present

- name: Add mongodb package repository
  apt_repository:
    repo: deb https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse
    state: present

- name: Update apt repository cache
  apt:
    update_cache: yes

- name: Install MongoDB
  apt:
    name: mongodb-org
    state: present

- name: Install python package (pymongo)
  pip:
    name:
      - pymongo

- name: Create directory for private key
  file:
    path: "{{ private_key_path }}"
    state: directory

- name: Create Private Key for mongo access
  copy:
    src: mongo-shard.pem
    dest: "{{ private_key_path }}/{{ private_key }}"
    mode: '0400'
    owner: mongodb
    group: mongodb
